apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-demo
  name: http-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-demo
  template:
    metadata:
      labels:
        app: http-demo
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - image: silenceper/http-demo:v0.1
        imagePullPolicy: IfNotPresent
        name: http-demo
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-demo
  name: http-demo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
